steps:
- name: node:12.16.3
  entrypoint: yarn
  args: ['install']
- name: node:12.16.3
  entrypoint: yarn
  args: ['build']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - app
  - deploy
  - version
  - 1
  - service
  - my-service
  - image-url=gcr.io/$PROJECT_ID/my-service
