export const errorResponse = {
    EMAIL_EXISTS: "EMAIL_EXISTS",
    TAXCODE_EXISTS: "TAXCODE_EXISTS",
    PHONE_EXISTS: "PHONE_EXISTS",

    EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
    PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",

    INVALID_PASSWORD: "INVALID_PASSWORD",
    USER_DISABLED: "USER_DISABLED",
    SERVER_ERROR: "SERVER_ERROR",
    USER_NOT_CONFIRMED: "USER_NOT_CONFIRMED",

    NOT_FOUND: "NOT_FOUND",
}