export const errorResponse = {
    EMAIL_EXISTS: "EMAIL_EXISTS",
    EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
    PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
    PHONE_EXISTS: "PHONE_EXISTS",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    USER_DISABLED: "USER_DISABLED",
    SERVER_ERROR: "SERVER_ERROR",
    USER_NOT_CONFIRMED: "USER_NOT_CONFIRMED",
    USER_NOT_FOUND: "USER_NOT_FOUND"
}